schemaVersion: 2.3.0
metadata:
    name: aib-devspaces
    tags:
        - Jumpstarter
        - Automotive
    language: C
projects:
    - name: aib-devspaces
      git:
          remotes:
              origin: https://github.com/rh-sdv-cloud-incubator/aib-devspaces-remote.git
components:
    - name: runtime
      container:
          image: quay.io/rh-sdv-cloud/aib-base-dev:latest
          mountSources: true
          args: ["tail", "-f", "/dev/null"]
          env:
              - name: KUBEDOCK_ENABLED
                value: "true"
              - name: KUBECONFIG
                value: "/home/user/.kube/config"
              - name: JMP_CLIENT_CONFIG_HOME
                value: "/home/user/.jumpstarter"
commands:
  - id: copy-jmp-client
    exec:
      component: runtime
      commandLine: "bash ./cp_jmp_client.sh"
      workingDir: ${PROJECT_SOURCE}
events:
  postStart:
    - copy-jmp-client
